name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-trivy:
    runs-on: ubuntu-latest
    # no dependencies so this job can run standalone

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vuln-lab:${{ github.sha }} .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "vuln-lab:${{ github.sha }}"
          format: table
          exit-code: "1"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true